.gitignore
.idea/deploymentTargetDropDown.xml
.idea/gradle.xml
.idea/misc.xml
apks/output-metadata.json
app/src/main/AndroidManifest.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/MainActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/AAmountFragment.java
app/src/main/res/layout/activity_entry.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/values-sw320dp-land-mdpi/dimens.xml
app/src/main/res/values-sw320dp-land-xhdpi/dimens.xml
app/src/main/res/values-sw320dp-land-xxhdpi/dimens.xml
app/src/main/res/values-sw320dp-port-hdpi/dimens.xml
app/src/main/res/values-sw320dp-port-mdpi/dimens.xml
app/src/main/res/values-sw320dp-port-xhdpi/dimens.xml
app/src/main/res/values-sw423dp-land-hdpi/dimens.xml
app/src/main/res/values-sw426dp-land-hdpi/dimens.xml
app/src/main/res/values-sw480dp-port-hdpi/dimens.xml
app/src/main/res/values-sw480dp-port/dimens.xml

https://pax-us.atlassian.net/browse/POSUI-38

Dev pos UI 38

---

.idea/misc.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/MainActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/signature/SignatureFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/AVSFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/EnterOrigTransDateFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/ExpiryFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/AAmountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/CashbackFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/TipFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/TotalAmountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/fleet/FleetDataFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/fsa/FSAAmountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/number/ANumFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/numbertext/ANumTextFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/text/ATextFragment.java

POSUI-51
All fragments containing EditText will request for touch focus. (Open up keyboard automatically)

Dev pos UI 51

---

.idea/misc.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/AVSFragment.java
app/src/main/res/layout/fragment_avs.xml

POSUI-56
address and zip verification editText inputType modified in code and xml

Dev pos UI 56

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/BaseEntryDialogFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/BaseEntryFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/EntryActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/AConfirmationDialogFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmServiceFeeDialogFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmSurchargeFeeDialogFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/information/DisplayTransInfoFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/option/AOptionsDialogFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/InputTextFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/ShowInputTextBoxFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/ShowSignatureBoxFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/security/ASecurityFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/security/InputAccountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/security/ManageInputAccountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/signature/SignatureFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/AVSFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/EnterOrigTransDateFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/ExpiryFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/AAmountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/CashbackFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/TipFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/TotalAmountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/number/ANumFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/numbertext/ANumTextFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/text/ATextFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/event/EntryConfirmEvent.java
app/src/main/res/layout/activity_entry.xml
app/src/main/res/layout/fragment_surcharge_fee.xml

POSUI 57
Hardware OK Button will work as a confirm button

Dev pos UI 57

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/UIFragmentHelper.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmSurchargeFeeDialogFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmSurchargeFeeFragment.java
app/src/main/res/layout/fragment_surcharge_fee.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

BPOSANDJAX-620
Modified the surcharge fee confirmation fragment according to FRD.

Dev bposandjax 620

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/EntryActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/security/InputAccountFragment.java

POSUI-49
POSLinkUI Demo app crashes on transaction abort on HZ BroadPOS applications

[POSUI-49]  POSLinkUI Demo app crashes on transaction abort on HZ BroadPOS applications

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/BaseEntryFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/EntryActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/AVSFragment.java

Focusing the zip using hard keyboard works now.

[POSUI-56] Keyboards swapped for Address and Zip code fields using POSLink UI

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/TipFragment.java

[POSUI-76] 
For tip other amount, $ sign should in input box
[POSUI-76]: https://pax-us.atlassian.net/browse/POSUI-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[POSUI-76] For tip other amount, $ sign should in input box

---

app/src/main/res/layout/fragment_pin.xml

[POSUI-87] Asterisks "*" that are hiding PIN are blending with entry data field and barely visible on A80 screen

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/EntryActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/UIFragmentHelper.java
app/src/main/java/com/paxus/pay/poslinkui/demo/status/StatusDialogFragment.java
app/src/main/res/values/strings.xml

Added broadcast reception support for InformationStatus.ENTER_PIN_STARTED.

[POSUI-90] Credit discover, visa and all Debit Insert transactions getting stuck on EMV Process Start until "Timeout" when POSLinkUI Demo is installed

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/security/InputAccountFragment.java

Preparing POSLinkUI-Demo in case host implements broadcast instead of startActivity.

[POSUI-91] POSLINK UI Demo is not receiving CARD_INSERT_REQUIRED and CARD_SWIPE_REQUIRED broadcast due to missing registrations

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/EntryActivity.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/text/amount/TipFragment.java
app/src/main/res/drawable/checkable_text.xml
app/src/main/res/layout-land/fragment_pin.xml
app/src/main/res/layout/fragment_checkable_item.xml
app/src/main/res/layout/fragment_pin.xml
app/src/main/res/layout/fragment_tip.xml
app/src/main/res/values-sw320dp-land-xhdpi/dimens.xml
app/src/main/res/values-sw423dp-land-hdpi/dimens.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/themes.xml

Hardkey bug solved on A35, Aries8
Better Layout on A30

[POSUI-106] [A80S] User has to hit green confirmation hard key button twice to confirm data entered on TIP screen

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/UIFragmentHelper.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/AConfirmationFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmBalanceFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmCardProcessResultFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmDCCFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ConfirmPrinterStatusFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/ReversePartialApprovalFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/confirmation/SupplementPartialApprovalFragment.java
app/src/main/res/values/strings.xml

@CallSuper needed in concrete confirmation fragments

Added ConfirmationEntry.ACION_CONFIRM_BALANCE

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/POSLinkStatusManager.java

Added category in sender at the last minute, missed category in receiver.

[POSUI-163] [BridgePay] When POSLink UI Demo is installed, CLEARMESSAGE command returns OK, but doesn't clear message on app screen

---

app/src/main/res/layout-land/fragment_input_account.xml
app/src/main/res/layout/fragment_input_account.xml

Jira: https://pax-us.atlassian.net/browse/POSUI-204

[POSUI-204] [Q10A POSLink UI] The 'Please Enter Card Number' message is cut off by the total amount line

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/ShowTextBoxFragment.java

https://pax-us.atlassian.net/browse/POSUI-245
*
Revised textLayout logic
w text
o text

POSUI-245 App does not display the QR code sent by the BroadPOS payment app for SHOWTEXTBOX command

---

app/src/main/res/layout/fragment_show_signature_box.xml
app/src/main/res/values/strings.xml

https://pax-us.atlassian.net/browse/POSUI-253
*
Refer to FDRC's related behavior.

POSUI-253 [A920] ShowTextBox command Confirm button text is display in two lines

---

.idea/misc.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/InputTextFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/utils/CurrencyUtils.java
app/src/main/res/layout/fragment_input_text.xml

https://pax-us.atlassian.net/browse/POSUI-225
Wrote TextWatcher for amounts, input type for passwords

[POSUI-225] Enhance app to display hint and keyboard based on the Input Text command Input Type value

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/BaseEntryFragment.java

https://pax-us.atlassian.net/browse/POSUI-269
*

[POSUI-269] The font size of the entered card number appears to be too small.

---

app/src/main/java/com/paxus/pay/poslinkui/demo/entry/option/SelectCashDiscountFragment.java
app/src/main/java/com/paxus/pay/poslinkui/demo/entry/poslink/ShowItemFragment.java

Remove Null Pointer Exception from SelectCashDiscount and ShowItem

---

app/build.gradle

Update version 20241206

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/paxus/pay/poslinkui/demo/utils/interfacefilter/EntryActionAndCategoryRepository.java

https://pax-us.atlassian.net/browse/POSUI-330
https://pax-us.atlassian.net/browse/POSUI-341
*
**330:**
https://github.com/user-attachments/assets/40be8efb-23a3-4be3-b05b-611fdc2db774
**341:**

[POSUI-330] [POSUI-341] Remove TRANS_FOR_ADJUST from intent-filter, Set default enableOtherPrompt to false.
